
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/elastic?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin
#    schema: classpath:data.sql
    data: classpath:data.sql
    sql-script-encoding: utf-8

  thymeleaf:
    suffix: .html
    prefix: classpath:templates/
    encoding: UTF-8
    mode: HTML5
    enabled: true
    servlet:
      content-type: text/html
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


