server:
  port: 80
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/elastic?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin

  thymeleaf:
    suffix: .html
    prefix: classpath:templates/
    encoding: UTF-8
    mode: HTML
    enabled: true
    servlet:
      content-type: text/html
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


